POST http://localhost:8081/products
Content-Type: application/json

{
  "name": "Apple",
  "price": "500",
  "quantity": "15"
}

###
GET http://localhost:8081/products

###
POST http://localhost:8081/orders
Content-Type: application/json

{
  "productId": "123123123",
  "userId": "111",
  "addressId": "321321",
  "quantity": "15"
}

###
GET http://localhost:8090/users/111
Content-Type: application/json