server:
  port: 8090

spring:
  main:
    banner-mode: off
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
